//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange_App.Model
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Windows.Media.Imaging;

    public partial class Image
    {
        public int ImageID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public byte[] ImageUrl { get; set; }
    
        public virtual Product Product { get; set; }
        public BitmapImage ImageBitmap
        {
            get { return ConvertByteArrayToBitmapImage(ImageUrl); }
            set {; }
        }


        public static BitmapImage ConvertByteArrayToBitmapImage(Byte[] bytes)
        {
            var stream = new MemoryStream(bytes);
            stream.Seek(0, SeekOrigin.Begin);
            var image = new BitmapImage();
            image.BeginInit();
            image.StreamSource = stream;
            image.EndInit();
            return image;
        }

    }
}
